spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fchaindb?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: labs123!@#
      connection-test-query: SELECT 1
