# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: fchain.com
    Template:
      Count: 1 
      Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.fchain.com
    Template:
      Count: 2
      Hostname: p{{.Index}}
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.fchain.com
    Template:
      Count: 2
      Hostname: p{{.Index}}
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.fchain.com
    Template:
      Count: 2
      Hostname: p{{.Index}}
    Users:
      Count: 1
