swagger: "2.0"
info:
  version: 1.0.0
  title: Hyperledger Fabric 1.4 Forensic chain API
  description: Simple Api Sample for to interact with HLF 1.4 NETWORK
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Balance
    description: Simple Balance Transfer Example
  - name: Fchain
    description: Simple Forensic Chain Example
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:

  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /fchain/addDocument:
    post:
      tags:
        - Fchain
      description: Fetch all examples
      parameters:
        - name: DocumentId
          in: body
          type: string
          description: an evidence unique Id
          required: true
        - name: DocumentType
          in: body
          type: string
          description: an evidence unique Id
          required: true
        - name: WriterId
          in: body
          type: string
          description: an evidence register
          required: true
        - name: WriteTime
          in: body
          type: string
          description: an evidence description
          required: true
        - name: Description
          in: body
          type: string
          description: the case id of this evidence
          required: true
        - name: CaseId
          in: body
          type: string
          description: the integrity of this evidence
          required: true
        - name: Hash
          in: body
          type: string
          description: the time of registration
          required: true
      responses:
        200:
          description: Returns all examples

  /fchain/addEvidence:
    post:
      tags:
        - Fchain
      description: Fetch all examples
      parameters:
        - name: EvidenceId
          in: body
          type: string
          description: an evidence unique Id
          required: true
        - name: RegisterId
          in: body
          type: string
          description: an evidence register
          required: true
        - name: Description
          in: body
          type: string
          description: an evidence description
          required: true
        - name: CaseId
          in: body
          type: string
          description: the case id of this evidence
          required: true
        - name: Hash
          in: body
          type: string
          description: the integrity of this evidence
          required: true
        - name: RegisterTime
          in: body
          type: string
          description: the time of registration
          required: true
      responses:
        200:
          description: Returns all examples


  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found


  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
