swagger: "2.0"
info:
  version: 1.0.0
  title: Hyperledger Fabric 1.4 Fchain  API
  description: Simple Api Sample for to interact with HLF 1.4 NETWORK
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Fchain
    description: Simple Forensic Chain Example
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:

  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

  evidenceRecord:
    required:
    - objectId
    - timestamp
    - registerTime
    - caseId
    - evidenceId
    - fileName
    - fileSize
    - eventType
    - eventUserId
    - eventUserOrg
    - description
    - evidenceHash
    properties:
      objectId:
        type: string
      timestamp:
        type: string
      registerTime:
        type: string
      caseId:
        type: string
      evidenceId:
        type: string 
      fileName:
        type: string
      fileSize:
        type: string
      eventType:
        type: string
      eventUserId:
        type: string
      eventUserOrg:
        type: string
      description:
        type: string
      evidenceHash:
        type: string

paths:

  /fchain/addEvidenceRecord:
    post:
      tags:
        - Fchain
      description: Fetch all examples
      parameters:
        - name: evidenceRecord
          in: body
          required: true
          schema:
            $ref: "#/definitions/evidenceRecord"
          description: an evidence
      responses:
        200:
          description: Returns all examples

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found


  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
